name: Tests and checks

on: push

jobs:
  check:
    name: Test python${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-20.04"
          - "windows-latest"
          - "macos-latest"
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e py${{ matrix.python }}
      - name: Run linters
        run: tox -e pre-commit
      - name: Run type checking
        run: tox -e mypy
