name: Tests and checks

on: push

jobs:
  check:
    name: Test python${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - "ubuntu-20.04"
          - "windows-latest"
          - "macos-latest"
        python:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        # Workaround from https://github.com/actions/runner-images/issues/9770
        exclude:  # Python < v3.8 does not support Apple Silicon ARM64.
          - python: "3.6"
            os: macos-latest
          - python: "3.7"
            os: macos-latest
        include:  # So run those legacy versions on Intel CPUs.
          - python: "3.6"
            os: macos-13
          - python: "3.7"
            os: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install tox
        run: pip install tox
      - name: Run tests
        run: tox -e py${{ matrix.python }}
      - name: Run linters
        run: tox -e pre-commit
      - name: Run type checking
        run: tox -e mypy
